# There should be some port:Seaports
PREFIX ports: <https://www.uktradeinfo.com/def/ports#>
PREFIX schema: <http://schema.org/>
ASK {
SELECT (COUNT(?a) AS ?ports) WHERE {
  ?a a ports:Seaport .
} HAVING (?ports > 0)
}
